# Generated by Django 3.0.5 on 2020-05-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0004_auto_20200516_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
